on: [push, pull_request]

name: CI

jobs:
  CI:
    name: CI_Node_${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [18, 20]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: ${{ matrix.version }}
      - name: Install
        run: yarn install
